# Generated by Django 5.1.6 on 2025-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_doctor',
            new_name='email_verificado',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Doctor', 'Doctor'), ('Administrador', 'Administrador')], default='Paciente', max_length=20),
        ),
    ]
