# Generated by Django 5.1.6 on 2025-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dias_restantes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
