# Generated by Django 5.1.6 on 2025-05-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_bloque', models.IntegerField(default=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora',
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to='citasMedicas.doctor')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasMedicas.jornadadiaria')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='bloque',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='citasMedicas.bloquehorario'),
        ),
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_horario', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_semanales', to='citasMedicas.doctor')),
                ('jornadas', models.ManyToManyField(to='citasMedicas.jornadadiaria')),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
