# Generated by Django 5.1.6 on 2025-05-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0002_cita_dias_restantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dias_restantes',
        ),
    ]
